questions = [
	"Who would alienate themselves and others?",
	"Who would kill for love?",
	"Who would win at ping pong?",
	"Who would win at fussball?",
	"Who would start their own business?",
	"Who would sell themselves to the highest bidder?",
	"Who would show most sympathy?",
	"Who would live fast and die young?",
	"Who would swear on their mother's life?",
	"Who would lie through their teeth?",
	"Who would paint a picture?",
	"Who would compose a symphony?",
	"Who would delude themselves?",
	"Who would travel the world?",
	"Who would unmask Batman?",
	"Who would live amongst the animals?",
	"Who would bark in anger?",
	"Who would bark in fear?",
	"Who would best control their bladder?",
	"Who would defeat their inner demons?",
	"Who would do better at maths?",
	"Who would sing surprisingly well?",
	"Who would be seduced by their own reflection?",
	"Who would travel the world and be disappointed by it?",
	"Who would ask a silly question?",
	"Who would declare a bold truth?",
	"Who would give you the finger?",
	"Who would mutter under their breath?",
	"Who would make a cup of tea?",
	"Who would read a trashy novel?",
	"Who would listen to bad pop?",
	"Who would go to an art gallery?",
	"Who would buy an expensive sandwich?",
	"Who would wear expensive clothes?",
	"Who would buy lunch?",
	"Who would decide the matter outright?",
	"Who would laugh in the other's face?",
	"Who would be content in themselves?",
	"Who would turn the other cheek?",
	"Who would fight with grave violence?"
]

questions.each do |q|
  Question.new( :text => q ).save
end